
DROP TABLE SEQUENCEMETA.SAMPLE_STORAGE;
DROP TABLE SEQUENCEMETA.SEQ_SOURCE_CELL;
DROP TABLE SEQUENCEMETA.SEQUENCE_ORGANISM;
DROP TABLE SEQUENCEMETA.SEQUENCE_SOURCE;

DROP TABLE SEQUENCEMETA.ISOLATE_PERSON;
DROP TABLE SEQUENCEMETA.ISOLATED_ORGANISM;

DROP TABLE SEQUENCEMETA.ISOLATE_LABORATORY;

DROP TABLE SEQUENCEMETA.PROJECT_CONTACT_PERSON;
DROP TABLE SEQUENCEMETA.Plasmid;
DROP TABLE SEQUENCEMETA.ISOLATE_PERSON;
DROP TABLE SEQUENCEMETA.PROJECT_ORGANISM;


DROP TABLE SEQUENCEMETA.ORGANISM_HOST;
DROP TABLE SEQUENCEMETA.OTHER_MEDIUM;
DROP TABLE SEQUENCEMETA.LABORATORY;
DROP TABLE SEQUENCEMETA.AIR;
DROP TABLE SEQUENCEMETA.CELL;
DROP TABLE SEQUENCEMETA.HOST;
DROP TABLE SEQUENCEMETA.HOST_INFOR;
DROP TABLE SEQUENCEMETA.LINK;
DROP TABLE SEQUENCEMETA.ORGANISM;
DROP TABLE SEQUENCEMETA.PERSON;
DROP TABLE SEQUENCEMETA.PROJECT;
DROP TABLE SEQUENCEMETA.PUBLICATION;
DROP TABLE SEQUENCEMETA.REPLICONS;
DROP TABLE SEQUENCEMETA.SEQUENCING;
DROP TABLE SEQUENCEMETA.SUBMISSION;
DROP TABLE SEQUENCEMETA.WATER_BODY;
DROP TABLE SEQUENCEMETA.ISOLATION_ENVIRONMENT;
